# Generated by Django 4.2.14 on 2025-10-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(unique=True)),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField()),
                ('unique_characters', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('character_frequency_map', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyzed_strings',
                'ordering': ['-created_at'],
            },
        ),
    ]
